In [3]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables ?

#### Ans Variable_listt -A list is a built-in data type in Python that can store a collection of items of different types. It is mutable, meaning you can modify its elements.
#### Array_list -It is also capable of storing a collection of elements, but unlike a list, an array is homogeneous.


In [4]:
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


### Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [10]:
get_data_type = lambda x: type(x)

print(list(map(get_data_type, list_)))
print('\n')
print(list(map(get_data_type, array_list)))

[<class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>]


[<class 'numpy.str_'>, <class 'numpy.str_'>, <class 'numpy.str_'>, <class 'numpy.str_'>, <class 'numpy.str_'>]


### Q3. Considering the following changes in the variable, array_list: array_list = np.array(object = list_, dtype = int) Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

In [13]:
array_list = np.array(object = list_, dtype = int)
print(list(map(get_data_type, list_)))
print(list(map(get_data_type, array_list)))

[<class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>]
[<class 'numpy.int64'>, <class 'numpy.int64'>, <class 'numpy.int64'>, <class 'numpy.int64'>, <class 'numpy.int64'>]


### Yes,array_list data has changed into "int" from "str".

### Q4. Write a code to find the following characteristics of variable, num_array:
 - (i) shape
 - (ii) size
 - Consider the below code to answer further questions:

In [15]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [17]:
num_array.shape

(2, 3)

In [18]:
num_array.size

6

### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [39]:
arr = np.random.randint(0,1,(3,3))
print(arr)
np.zeros((3,3))

[[0 0 0]
 [0 0 0]
 [0 0 0]]


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Q6. Create an identity matrix of shape (5,5) using numpy functions?
 [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])